---
- name: long running job
  gather_facts: false
  hosts: all
  serial: 10
  strategy: free
  tasks:
    - name: run a command
      command: "./firstcommand {{ inventory_hostname }}" 
      delegate_to: localhost

    - name: run a second command
      command: "./secondcommand {{ inventory_hostname }}" 
      delegate_to: localhost
  
